run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/randompic/api
  misspell:
    locale: US
  gosec:
    excludes:
      - G404 # weak random generator acceptable for non-crypto use

issues:
  exclude-use-default: false
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true